trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/*

steps:
- task: Docker@2
  displayName: Build Image
  inputs:
    command: build
    arguments: --build-arg KEYVAULT_URL=$(KEYVAULT_URL) --build-arg KEYVAULT_CLIENT_ID=$(KEYVAULT_CLIENT_ID) --build-arg KEYVAULT_CLIENT_KEY=$(KEYVAULT_CLIENT_KEY) --build-arg KEYVAULT_TENANT_ID=$(KEYVAULT_TENANT_ID)
    repository: todoapp
    Dockerfile: Dockerfile
    containerRegistry: acr 
    tags: |
      v$(Build.BuildId)
      latest
      
- task: Docker@2
  displayName: Push Image
  inputs:
    command: 'push'
    repository: todoapp
    containerRegistry: acr
    tags: |
      v$(Build.BuildId)
      latest
